---
- hosts: webservers
  sudo: yes
  vars:
    document_root: /var/www/doctrine-website-sphinx
  tasks:
    - name: Checkout Website
      git: >
        repo=git@github.com:doctrine/doctrine-website-sphinx.git
        dest={{ document_root }}

    - name: Install Sphinx Dependencies
      apt: >
        pkg={{ item }}
      with_items:
        - python-pip
        - python-yaml

    - name: Install Tinkerer
      pip: name=tinkerer

    - name: Download Composer
      get_url: >
        dest={{ document_root }}/composer.phar
        url=http://getcomposer.org/composer.phar

    - name: Update Composer
      command: >
        php composer.phar update
        chdir={{ document_root }}

    - name: Regenerate projects.yml from Github Data
      command: >
        php bin/build-projects.php
        chdir={{ document_root }}

    - name: Build css
      command: >
        lessc site/_themes/doctrine/static/bootstrap-theme.less > site/_themes/doctrine/static/bootstrap-theme.css

    - name: Build Website
      command: >
        tinker -b
        chdir={{ document_root }}/site

    - name: Create API Directory
      file: >
        path={{ document_root }}/pages/build/api
        state=directory

    - name: Generate API Documentation
      command: >
        php bin/build-apidocs.php pages/build/api
        chdir={{ document_root }}

    - name: Symlink API to HTML root
      file: >
        src={{ document_root }}/pages/build/api
        dest={{ document_root }}/site/blog/html/api
        state=link

    - name: Copy Favicon
      command: >
        cp favicon.ico site/blog/html/favicon.ico
        chdir={{ document_root }}

    - name: Link RSS Feed to .xml file
      file: >
        src={{ document_root }}/site/blog/html/rss.html
        dest={{ document_root }}/site/blog/html/rss.xml
        state=link

    - name: Move Pages to Document Root
      shell: >
        cp site/blog/html/* pages/build/current -R
        chdir={{ document_root }}

    - name: Make www-data owner
      command: >
        chown www-data.www-data pages/build/current -R
        chdir={{ document_root }}

